version: '2'
services:

  wift-mock-server:
    image: openjdk:8-jre
    networks:
      wift-network:
        aliases:
        - wift.mock.server
    container_name: wift-mock-server
    ports:
     - "8251:8251"
    volumes:
     - ./target:/bin
     - ./target/test-classes/__files:/__files
     - ./target/test-classes/mappings:/mappings
    environment:
     - WIREMOCK_ROOTDIRECTORY=.
    command: java -jar /bin/qa-mock-wift-0.0.1-SNAPSHOT.jar

networks:
  wift-network:
