# Makefile.particulars -- changing these should be all you need to do

# Set the name of the build image
export IMAGE_NAME := qa-mock-wift

# The file containing the semantic versioning number of this image.
# See https://semver.org/
export BUILD_VERSION_FILE := target/classes/build.version